system:
    CUDA_VISIBLE_DEVICES: '1'
    num_cpu: 10
    random_seed: 13

log:
    log_interval: 10
    checkpoint_dir: '../models/'

model: 
    name: 'Inception'

optimizer:
    lr: +1e-5

train:
    epochs: 5
    batch_size: 32

validation:
    batch_size: 512

dataset:
    dir: '/home/d/pancreas/box_data'
    csv: '/home/d/pancreas/raw_data/data_list.csv'
    input_dim: [50, 50, 1]  # HWC
