system:
    CUDA_VISIBLE_DEVICES: '1'
    GPU_memory_fraction: 0.5
    num_cpu: 10
    random_seed: 13

log:
    log_interval: 10
    checkpoint_dir: '../log/'
    model_dir: '../models/'
    result_dir: '../result/'

model:  
    name: 'simple_cnn_sigmoid'
    fix_layer: 0
    origin_name: 'test_mix_right_5'

optimizer:
    lr: +1e-3 # default: +1e-3

train:
    epochs: 200
    batch_size: 2560

validation:
    batch_size: 512

dataset:
    dir: '/data2/pancreas/box_data/wanyun'
    csv: '/data2/pancreas/Nifti_data/data_list.csv'
    holger: '/data2/pancreas/results/tmp'
    input_dim: [50, 50, 1]  # HWC
    stride: 25

    NTUH_split_H: [240, 80, 0]
    NTUH_split_C: [240, 80, 0]
    PancreasCT_split: [0, 0, 17]
    MSD_split: [0, 0, 56]
    #NTUH_split_H: [0, 0, 80]
    #NTUH_split_C: [0, 0, 80]
    #PancreasCT_split: [12, 4, 17]
    #MSD_split: [42, 14, 56]
    
    seed: 1
    load: 'box'

comet:
    api_key: 'vxjwm9gKFuiJaYpfHDBto3EgN'
    project_name: 'general'
    workspace: 'tinghui'
