system:
    CUDA_VISIBLE_DEVICES: '0'
    GPU_memory_fraction: 0.5
    num_cpu: 10
    random_seed: 1

log:
    log_interval: 10
    checkpoint_dir: '../log/'
    model_dir: '../models/'
    result_dir: '../result/'

model:  
    name: 'simple_cnn_sigmoid'
    origin_name: 'test_mix_right_5'

optimizer:
    lr: +1e-3 # default: +1e-3

train:
    epochs: 200
    batch_size: 2560

validation:
    batch_size: 512

dataset:
    dir: '/data2/pancreas/box_data/wanyun/cv_10/'
    csv: '/data2/pancreas/Nifti_data/data_list.csv'
    holger: '/data2/pancreas/results/tmp'
    input_dim: [50, 50, 1]  # HWC
    stride: 25
    seed: 1
    load: 'box'

comet:
    api_key: 'vxjwm9gKFuiJaYpfHDBto3EgN'
    project_name: 'general'
    workspace: 'tinghui'
