dataset:
  csv: /home/d/pancreas/raw_data/data_list.csv
  dir: /home/d/pancreas/resample115_box_data
  input_dim: [50, 50, 1]
log: {checkpoint_dir: ../models/, log_interval: 10}
model: {name: ResNet}
optimizer: {lr: 1e-05}
system: {CUDA_VISIBLE_DEVICES: '1', num_cpu: 10, random_seed: 13}
train: {batch_size: 32, epochs: 5}
validation: {batch_size: 512}
