system:
    CUDA_VISIBLE_DEVICES: '0'
    GPU_memory_fraction: 0.5
    num_cpu: 10
    random_seed: 13

log:
    log_interval: 10
    checkpoint_dir: '../log/'
    model_dir: '../models/'
    result_dir: '../result/'

model:  
    name: 'simple_cnn_sigmoid_keras'

optimizer:
    lr: +1e-3 # default: +1e-3

train:
    epochs: 200
    batch_size: 128

validation:
    batch_size: 512

dataset:
    dir: '/home/d/pancreas/box_data'
    csv: '/home/d/pancreas/raw_data/data_list.csv'
    input_dim: [50, 50, 1]  # HWC

comet:
    api_key: 'vxjwm9gKFuiJaYpfHDBto3EgN'
    project_name: 'general'
    workspace: 'tinghui'
